In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('/kaggle/input/used-car/Used Car Dataset.csv')
df.head()

#importing datasets

Unnamed: 0  seats  kms_driven  manufacturing_year  mileage(kmpl)  \
0           0      5       56000                2017           7.81   
1           1      5       30615                2020          17.40   
2           2      5       24000                2018          20.68   
3           3      5       18378                2019          16.50   
4           4      5       44900                2019          14.67   

   engine(cc)  max_power(bhp)  torque(Nm)  price(in lakhs)  
0        2996            2996         333            63.75  
1         999             999        9863             8.99  
2        1995            1995         188            23.75  
3        1353            1353       13808            13.56  
4        1798            1798       17746            24.00

In [5]:
df.drop(df.columns[[0]],axis=1,inplace=True)

#drop column 0 as it is not containing any relavant data, it just have index number which is not required for model training

In [6]:
df.head()

seats  kms_driven  manufacturing_year  mileage(kmpl)  engine(cc)  \
0      5       56000                2017           7.81        2996   
1      5       30615                2020          17.40         999   
2      5       24000                2018          20.68        1995   
3      5       18378                2019          16.50        1353   
4      5       44900                2019          14.67        1798   

   max_power(bhp)  torque(Nm)  price(in lakhs)  
0            2996         333            63.75  
1             999        9863             8.99  
2            1995         188            23.75  
3            1353       13808            13.56  
4            1798       17746            24.00

In [7]:
np_array=df.to_numpy()
np_array[:1,]

#convert DataFrame into numpy array
#becase in model.fit() we pass data as an array not as DataFrame

array([[5.000e+00, 5.600e+04, 2.017e+03, 7.810e+00, 2.996e+03, 2.996e+03,
        3.330e+02, 6.375e+01]])

In [8]:
x=np_array[:,:-1]
y=np_array[:,-1]

x[:1,:]

#extracting input columns/independent variable columns and output column/independent variable column
#x containing input columns data
#y containing output columns data

array([[5.000e+00, 5.600e+04, 2.017e+03, 7.810e+00, 2.996e+03, 2.996e+03,
        3.330e+02]])

In [9]:
y

array([63.75,  8.99, 23.75, ...,  5.85,  4.75,  6.1 ])

In [10]:
x.shape

(1490, 7)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=8)

#spliting data into 2 parts: training data and testing data

In [12]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1192, 7)
(298, 7)
(1192,)
(298,)


# ***model training using LinearRegression class of sci-kit learn***

In [13]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

#importing LinearRegression class and make the object of it

In [14]:
lr.fit(x_train,y_train)

#model training

LinearRegression()

In [15]:
x_test[:3,]

array([[5.0000e+00, 8.9002e+04, 2.0110e+03, 1.7500e+01, 1.1970e+03,
        1.1970e+03, 8.5800e+02],
       [7.0000e+00, 1.3800e+05, 2.0170e+03, 1.6000e+01, 2.1790e+03,
        2.1790e+03, 1.4000e+02],
       [5.0000e+00, 8.7217e+04, 2.0110e+03, 1.7000e+01, 1.4970e+03,
        1.4970e+03, 1.1866e+06]])

In [16]:
lr.predict(x_test[:3,])

#model testing

array([1062.50345518, -139.03439196,  123.96228759])

In [17]:
y_test[:3]

array([2.37, 6.95, 3.73])

In [26]:
print(lr.coef_)
print(lr.intercept_)

#printing weights and bias of predicted line

[ 9.94985181e+00 -3.33797899e-03 -1.58530220e+02  1.06644304e+00
 -5.37954823e-02 -5.37954824e-02 -7.68876323e-04]
320224.89594353037


# ***using AI's Linear Regression class***

# B = (X . X^T)^-1 . X^T .Y

In [18]:
import numpy as np

In [19]:
class AI_Linear_Regression:
    def __init__(self):
        self.coef_=None
        self.intercept_=None
        self.B=None
        
    def fit(self,x,y):
        x=np.insert(x,0,1,axis=1)
        self.B = np.linalg.inv(np.dot(x.T,x)).dot(x.T).dot(y)
        print(self.B)
        self.coef_=self.B[1:]
        self.intecept_=self.B[0]
        
    def predict(self,x):
        y_predict = np.dot(x,self.coef_) + self.intercept_
        print(y_predict)
    
# defining my own Linear Regression class capable to do simple as well as multiple linear regression

In [20]:
alr = AI_Linear_Regression()

#create object of class

In [21]:
print(x_train.shape)
print(y_train.shape)

(1192, 7)
(1192,)


In [22]:
x_train[:1,]

array([[4.0000e+00, 5.8000e+04, 2.0150e+03, 1.6770e+01, 2.9670e+03,
        2.9670e+03, 2.4674e+04]])

In [23]:
y_train[:1,]

array([29.75])

In [24]:
alr.fit(x_train,y_train)

#training model

LinAlgError: Singular matrix

In [ ]:
alr.predict(x_test[:3,])

#testing model

In [ ]:
y_test[:3]

In [ ]:
print(alr.coef_)
print(alr.intercept_)

#print weights and bias predicted line